services:
    sqwok:
        image: local/sqwok:latest
        build: .
        environment:
            COLORTERM: truecolor # remove this if your host terminal does not support 24-bit color
            SQWOK_SERVER: https://sqwok.fixbase.io
        volumes:
            - sqwok-data:/home/sqwok/.sqwok

volumes:
    sqwok-data:
